# --- General options --- #

# Name of website
title: Home

# Short description of your site
description: Professional webpage

# Use Minima theme
# theme: minima

# --- Local development options ---
# If your website is hosted locally rather than on GitHub, then you need to uncomment the next two parameters to set the url and baseurl
# *** If you're not sure what this means, leave this section as it is ***

# url is the website domain URL without a trailing slash
#url: "https://example.com"
#baseurl: ""
avatar: "/img/photo_modif.jfif"

# --- Navigation bar options --- #

# Custom navigation links
navbar-links:
  Research: "research"
  Softwares: "software/"
  Teaching: "teaching/"
  Contact: "contact/"


# --- Logo --- #

# Image to show in the navigation bar - works best with a square image
# Remove this parameter if you don't want an image in the navbar
avatar: "/assets/img/avatar-icon.png"

# By default, the image is cut into a circle. You can disable this behaviour by setting 'round-avatar: false'
round-avatar: true

# --- Footer options --- #

author: Mathilde Sautreuil

# Social network links
social-network-links:
  email: "mathilde.sautreuil@gmail.com"
  github: mathildesautreuil
  researchgate: Mathilde-Sautreuil
  linkedin: mathilde-sautreuil
  google-scholar: citations?user=fNn3adkAAAAJ&hl=fr

# --- Web Statistics Section --- #

# Google Analytics ID
google_analytics: "mathilde sautreuil"

# --- Misc --- #

# Excerpt Word Length
excerpt_length: 50

title-separator: "-"

# Ruby Date Format
date_format: "%B %-d, %Y"

# --- Jekyll options --- #

timezone: "Europe/Paris"
markdown: kramdown
highlighter: rouge
permalink: /:year-:month-:day-:title/
paginate: 5

kramdown:
  input: GFM

# Default YAML values (for posts and pages)
defaults:
  - 
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true
  - 
    scope:
      path: ""
    values:
      layout: "page"
      show-avatar: true


# --- Colours / background image --- #

# Personalize the colours in your website. Colour values can be any valid CSS colour

navbar-col: "#EAEAEA"
navbar-text-col: "#404040"
navbar-border-col: "#DDDDDD"
page-col: "#FFFFFF"
text-col: "#404040"
link-col: "#008AFF"
hover-col: "#0085A1"
footer-col: "#EAEAEA"
footer-text-col: "#777777"
footer-link-col: "#404040"

# Alternatively, the navbar, footer, and page background can be set to an image
# instead of colour

#navbar-img: "/assets/img/bgimage.png"
#footer-img: "/assets/img/bgimage.png"
#page-img: "/assets/img/bgimage.png"

# Suggest a colour for mobile browsers to use as the browser's theme. This is only supported by a few mobile browsers.
#mobile-theme-col: "#0085A1"

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag
