# --- General options --- #

# Name of website
title: Home

# Short description of your site
description: Professional webpage

# Use Minima theme
theme: minima

# --- Local development options ---
# If your website is hosted locally rather than on GitHub, then you need to uncomment the next two parameters to set the url and baseurl
# *** If you're not sure what this means, leave this section as it is ***

# url is the website domain URL without a trailing slash
#url: "https://example.com"
#baseurl: ""

# --- Navigation bar options --- #

# Custom navigation links
navbar-links:
  Research: "research"
  Softwares: "software/"
  Teaching: "teaching/"
  Contact: "contact/"

# --- Footer options --- #

author: Mathilde Sautreuil

# Social network links
social-network-links:
  email: "mathilde.sautreuil@gmail.com"
  github: mathildesautreuil
  researchgate: Mathilde-Sautreuil
  linkedin: mathilde-sautreuil
  google-scholar: citations?user=fNn3adkAAAAJ&hl=fr

# --- Web Statistics Section --- #

# Google Analytics ID
google_analytics: "mathilde sautreuil"

# --- Misc --- #

# Excerpt Word Length
excerpt_length: 50

title-separator: "-"

# Ruby Date Format
date_format: "%B %-d, %Y"

# --- Jekyll options --- #

timezone: "Europe/Paris"
markdown: kramdown
highlighter: rouge
permalink: /:year-:month-:day-:title/
paginate: 5

kramdown:
  input: GFM

# Default YAML values (for posts and pages)
defaults:
  - 
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true
  - 
    scope:
      path: ""
    values:
      layout: "page"
      show-avatar: true

plugins:
  - jekyll-paginate
  - jekyll-sitemap
