# --- General options --- #

# Name of website
title: Home

# Short description of your site
description: Professional webpage

# Use Cayman theme
theme: cayman

# --- Local development options ---
# Uncomment and modify if you host locally or need custom URL configurations

#url: "https://example.com"
#baseurl: ""

# --- Navigation bar options --- #

# Custom navigation links
navbar-links:
  Research: "research"
  Softwares: "software/"
  Teaching: "teaching/"
  Contact: "contact/"

# --- Footer options --- #

# Author name to show in the footer
author: Mathilde Sautreuil

# Social network links (Cayman theme doesn't display them by default)
social-network-links:
  email: "mathilde.sautreuil@gmail.com"
  github: mathildesautreuil
  researchgate: Mathilde-Sautreuil
  linkedin: mathilde-sautreuil
  google-scholar: citations?user=fNn3adkAAAAJ&hl=fr

# --- Web Statistics Section --- #

# Google Analytics ID
google_analytics: "mathilde sautreuil"

# --- Misc --- #

# Excerpt Word Length
excerpt_length: 50

# Character used to separate site title and description in the HTML document title
title-separator: "-"

# Ruby Date Format
date_format: "%B %-d, %Y"

# --- Jekyll options --- #

timezone: "Europe/Paris"
markdown: kramdown
highlighter: rouge
permalink: /:year-:month-:day-:title/
paginate: 5

kramdown:
  input: GFM

# Default YAML values (for posts and pages)
defaults:
  - 
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true
  - 
    scope:
      path: ""
    values:
      layout: "page"
      show-avatar: true

plugins:
  - jekyll-paginate
  - jekyll-sitemap
